### PR TITLE
Changed basegrid object to not take x, y and inputs and instead infer…

### LINKED ISSUE #84: remove dependency on Np1DArray, Np2DArray
These objects allow representations of numpy arrays as pydantic objects. They are the input type for the basegrid object. 

We need x and y attributes for that base object for a lot of the logic to work. However, none of the downstream objects require these as inputs. Having them as first class pydantic attributes means that any serialised object includes these as yaml representations of numpy arrays which is really ugly. I suggest we remove these as inputs, and just make them an abstract property instead. 

I'll have a play with it and propose something

### PR DESCRIPTION
**Pull request by tomdurrant**
… as properties. Changes in swan and schism to reflect this

closes #84

### CODE REVIEW

**Comment by tomdurrant** [comment]
This removes the depency on NDArray with was causing numpy v2 issues, thus fixing #97

**Comment by tomdurrant** [comment]
@benjaminleighton @rafa-guedes this should be good to go now

**Comment by rafa-guedes** [comment]
pydantic_numpy is actually used in a couple of swan components as well. Let me perhaps have a look at this as well @benjaminleighton and @tomdurrant to see if I can find a workaround to stop using those there as well. I'll merge this then.

**Comment by rafa-guedes** [comment]
pydantic_numpy can be installed alongside numpy<2 if it is pinned to pydantic_numpy<6. I'm going to merge this as is without removing pydantic_numpy requirement as it is used in some swan components and is rather useful to validate some input types.

**Pull request merged**
