### PR TITLE
Implemented autogeneration of gr3 files

### PR DESCRIPTION
**Pull request by tomdurrant**
@hot007 Vanessa, this is not quite ready to merge, but just creating a pull request to facilitate discussion. Couple of questions below

### CODE REVIEW

**Comment by tomdurrant** [comment]
hgrid.ll is identical to hgrid.gr3 in the template, are both needed?

**Comment by tomdurrant** [comment]
Can you guys just check that datatypes for each of the generated gr3 files? I.e. the second argument in the Union, int or float

**Comment by hot007** [comment]
> hgrid.ll is identical to hgrid.gr3 in the template, are both needed?

@VHernaman confirms that they are identical for these grids because we're using spherical coords but they would differ for a cartesian grid.

Regarding the datatypes, a) I don't know off the top of my head (Vanessa might!), but b) where would we find where that's defined? I just had a quick look at your commit https://github.com/rom-py/rompy/pull/58/commits/89fab9bd3bd29262e8eb255b1d06050076350477 above and it didn't leap out at me... also I'm a bit unclear what's happening there, you've got a gr3 generator defined for half a dozen of the possible gr3s but not, e.g., drag/rough/manning, though I can see the validator check that only one of them is present. I'm probably just missing the bit of code where they're created. I'm not the best at reading code snippets from commit logs, can you please point me to where I should be looking? Thanks!

**Comment by tomdurrant** [comment]
Thanks @hot007. I have added a symlink hgrid.ll symlink to to hgrid.gr3 if the former is not supplied. 

I think drag, rough and manning are there, but I will double check.  There is a fair bit of parallel dev going on, so I am going to merge this back in to the schism branch and I will followup with the outstanding questions from there.

**Pull request merged**
